### ISSUE TITLE
Enable Matcher for path

### ISSUE THREAD

**Issue by lutzj82** [DiUS/pact-consumer-swift#21]
I have a PUT request that takes uses a UUID as part of the path, but since the path argument is a String, I can't pass it a Matcher [String: AnyObject]

example of what I'd like to do:

```
let putReq = Matcher.term(matcher: "/^\\/v1\\/start\\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i",
                                  generate: "/v1/start/\(uuid)/")

mockService.given("a record exists")
            .uponReceiving("a request to invoke start action for new instance")
            .withRequest(method:.PUT, path: putReq)
            .willRespondWith(status:200)
```

**Comment by andrewspinks** [comment]
@lutzj82 Hmm, that sounds like a problem. I should have time to look at it tomorrow.

**Comment by andrewspinks** [comment]
@lutzj82 I pushed a fix to master. Let me know if it works for you.

**Comment by lutzj82** [comment]
I'm still using XCode 7.3 and swift 2 with Carthage, I'll have to see what you did.

**Comment by andrewspinks** [comment]
@lutzj82 Although the change that I made "seems" to work from the consumer point of view, I noticed that the pact file generated is missing the matcher details. It looks to be a bug in the mock service, and I've raised a bug there https://github.com/bethesque/pact-mock_service/issues/55 This may mean that what you are trying to achieve won't work until that bug is fixed.

As a side note, I am currently working at removing the dependency on the ruby mock service in favour of a native library. The native mock service will be the path forward for most of the pact clients and should not have this problem.

**Comment by andrewspinks** [comment]
@lutzj82 OK, it seems I am wrong, and it is working as designed. Let me know if you would like me to retrofit the fix back for swift 2.2

**Comment by lutzj82** [comment]
@andrewspinks, So I took your code changes and added it as an extension method on my end and it worked! If you could, that'd be great as I wasn't planning on the upgrade for a little while. If not, I will use the extension until then.

**Comment by andrewspinks** [comment]
@lutzj82 Awesome! I'll try and retrofit it sometime this week. I'll leave this open until I've released the new version.
