### ISSUE TITLE
Test fails in physical device

### ISSUE THREAD

**Issue by vijay2pvk** [DiUS/pact-consumer-swift#49]
Hi, Can we run the pact tests in physical device? I am getting below errors

"Verification error (check build log for mismatches): Error" 
"Waited more than 1.0 seconds"

Even tested with PactSwiftExample project & getting same error.

**Comment by surpher** [comment]
Hi Vijay. Is [PactMockService](https://github.com/pact-foundation/pact-ruby-standalone/releases) running at the time you are trying to run your tests?

Worth noting what `url` you are using in your tests? The `helloProvider: MockService` defaults to `localhost`, so that means your physical device would need to run your _MockService_ as the tests would call `localhost`. If you must run your tests using a physical device, make sure to instantiate your `PactVerificationService` with a `url` where you are hosting your _MockService_ and that your physical device can access it/communicate with it.

Also, here is a very good run through on how to setup your Xcode project: [Contract Testing with Pact](https://medium.com/@DoorDash/contract-testing-with-pact-7cf108ced8c4)

**Comment by vijay2pvk** [comment]
Hi Marko. I am able to run in **iOS simulator successfully**. I have issue only when i run in **Physical device**. I have few doubts

1) How will i know that PactMockService is running?
2) Where this PactMockService will run? locally in device or Mac? How to implement

Here is the code snippet which i am using

let verificationService = PactVerificationService(url: "http://localhost", port: 1_234)
        provider = MockService(provider: "SomeName Provider", consumer: "SomeName iOS", pactVerificationService: verificationService)

**Comment by andrewspinks** [comment]
@vijay2pvk In the xcode setup instructions you probably added a pre-action step which contains the  command to start the mock service and set the port. i.e.
```pact-mock-service start --pact-specification-version 2.0.0 --log "${SRCROOT}/tmp/pact.log" --pact-dir "${SRCROOT}/tmp/pacts" -p 1234```
The last parameter `-p 1234` specifies that it will run on port 1234. i.e. The mock server should be running on http://localhost:1234 of your *mac*. 

When running in the simulator the ip address of the simulator and the host computer are the same and using `PactVerificationService(url: "http://localhost", port: 1234)` works. 

However, if running on device, then the host machine is different and localhost will not work. You must then specify the ip address of your mac, where the mock service is running.

Pact is a tool for testing the contracts between a client and server.  I would recommend that you test on a simulator, keep your pact tests localized to only testing your server calling code. There should be nothing that is device specific in your tests that warrant running on a device. This will make the tests simpler, breakages easier to debug, and less likely to be flaky due to device / UI issues.

**Comment by bethesque** [comment]
If you're running the mock service on a different host, you'll also need to start it up with `--host 0.0.0.0` so that it is externally accessible. By default, it binds to localhost.

But as Andy says, you don't typically use the mock service with real devices.  The best use of pact is to test just the code in your consumer that is responsible for calling your provider https://docs.pact.io/best_practices/consumer#use-pact-for-isolated-unit-tests

**Comment by vijay2pvk** [comment]
Thanks Marko, Andrew & Beth for your quick response.

**Comment by vivekthambikannu** [comment]
Hi, I am using pact consumer in my project, real time device only able to run my project unable to run in simulator.
my local ip address is = 120.138.12.180, iam getting this error 
failed - Error setting up pact: The request timed out.
failed - Verification error (check build log for mismatches): The request timed out.
**My code**
 let verificationService = PactVerificationService(url: "http://120.138.12.180", port: 1234)
        mockService = MockService(provider: "Provider", consumer: "iOS", pactVerificationService: verificationService)
