### ISSUE TITLE
Remove Nimble dependency

### ISSUE THREAD

**Issue by surpher** [DiUS/pact-consumer-swift#57]
Almost every new Xcode and swift version breaks due to downstream dependencies. 
Reducing number of dependencies will reduce unnecessary breakages and reduce maintenance work.

This issue focuses on removing hard dependency on Quick/Nimble in the main framework. 
Move dependency into test targets only so it's not propagated to end users of this Framework.

**Comment by rubencagnie** [comment]
I'm currently investigating Pact and stumbled upon this library. It's working really well (great job!), but the fact that it relies on `Nimble` is a bit tedious, because we don't use it in our App.

After looking into the code, the dependency doesn't really seem too big. I actually did the work to remove the Nimble dependency in the framework (as well as `OHHTTPStubs`). There would still be the dependency on `Nimble` for the test target, but not for the library itself. This would be be great for consumers that don't use Nimble (which is my case).

The problem with this change is that this would be a breaking change, as the `MockService` would no longer have the `Nimble` dependency and the clients would have to add the `error errorReporter` explicitly. Would that be ok? My proposal would be that you could add another library that would just have the Nimble specific goodies baked in (e.g. `pact-consumer-swift-nimble`) which then depends on `pact-consumer-swift` as well.

Let me know what you think!

**Comment by huwr** [comment]
To me this sounds quite promising; I had a similar approach but I didn't quite get there. 

I was trying to use dispatch groups to replace the `waitUntil` function. I was having trouble there though. I think the `wait(timeout:)` was not firing because I didn't have a `NSRunLoop`… (not sure yet though)

To replace `fail` I hadn't come up with anything yet. Is that where you need your `errorReporter`?

**Comment by rubencagnie** [comment]
Both for `wait` and `fail`, XCTest has a solution. I’ll try to get a PR up later today or tomorrow so you can see the proposed implementation

**Comment by surpher** [comment]
The thing with Nimble's `fail(message:file:line:)` is that it reports the failed test at a specific line (eg. `mockService.run {...}) where as `XCTFail()` will trigger in the file and on the line where `XCTFail()` is called

**Comment by huwr** [comment]
Thanks!
