### ISSUE TITLE
Improve swiftlint reporting

### ISSUE THREAD

**Issue by andrewspinks** [DiUS/pact-consumer-swift#90]
When there is a linting issue while running in travis-ci, the output is hidden in the build log file. This makes it hard to identify what went wrong and can make it confusing and frustrating for contributors.

**Comment by surpher** [comment]
Might be `xcpretty` being dumb. Maybe we should try with  `[xcbeautify](https://github.com/thii/xcbeautify)`. I'm not sure if it is available on TravisCI.org mac runners bu default though.

In `scripts/build.sh` the command to build and test `... xcodebuild ... | xcbeautify` instead of `| xcpretty -c`
